web:
    container_name: local-dev-php
    image: hsg377/php71:latest
    #build: .
    ports:
        - "80:80"
        - "443:443"
    environment:
        - IS_DEV=Y
    volumes:
        - ./etc/vhost.conf:/etc/httpd/conf.d/vhost.conf
        - /mnt/d/workspace:/var/www/app # WSL2 Path
        #- /D/workspace:/var/www/app # Mount Path
